version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: always
    env_file:
      - dev.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_local_data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: redis-local
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "no" ]
    volumes:
      - redis_local_data:/data

  mongodb:
    image: mongo:7
    container_name: mongo-local
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: chatdb

  chat-server-1:
    image: chat-server-application:latest
    container_name: chat-server-1
    depends_on:
      - mysql
      - redis
      - mongodb
    env_file:
      - dev.env
    environment:
      SERVER_PORT: 7001
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
      SPRING_REDIS_HOST: redis
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/chatdb
    ports:
      - "7001:7001"

  chat-server-2:
    image: chat-server-application:latest
    container_name: chat-server-2
    depends_on:
      - mysql
      - redis
      - mongodb
    env_file:
      - dev.env
    environment:
      SERVER_PORT: 7002
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
      SPRING_REDIS_HOST: redis
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/chatdb
    ports:
      - "7002:7002"

volumes:
  mysql_local_data:
  redis_local_data:
  mongo_data:
